# Generated by Django 4.1.6 on 2023-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='brief',
            field=models.TextField(default='This is a brie'),
        ),
    ]
